# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flag' do
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  pod 'SwiftGen'
  pod 'SwiftLint'
end
